SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `cpandatesters` DEFAULT CHARACTER SET binary;
USE `cpandatesters`;

CREATE TABLE IF NOT EXISTS `reports` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `grade` varbinary(4) DEFAULT NULL,
  `distname` varbinary(64) DEFAULT NULL,
  `distauth` varbinary(64) DEFAULT NULL,
  `distver` varbinary(32) DEFAULT NULL,
  `compver` varbinary(32) DEFAULT NULL,
  `backend` varbinary(16) DEFAULT NULL,
  `osname` varbinary(32) DEFAULT NULL,
  `osver` varbinary(32) DEFAULT NULL,
  `arch` varbinary(64) DEFAULT NULL,
  `raw` blob,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=binary AUTO_INCREMENT=7 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
